spring.application.name=spring-6-rest-mvc
logging.level.com.springframework=debug
# spring.profiles.active=localmysql

# Disable Flyway for h2 in-memory database(default profile)
spring.flyway.enabled=false

# http basic authentication
# spring.security.user.name=user1
# spring.security.user.password=password

# OAuth2 authentication
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# logging.level.org.springframework.security=trace

# These are used to create the datasource and JPA properties for MySQL database connection

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop-and-create.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=drop-and-create.sql